// (C) Copyright 2002-2007 by Autodesk, Inc. 

// IntellectRoadDesign.idl : IDL source
//
// This file will be processed by the MIDL tool to
// produce the type library (NBIMIntellectRoadDesign.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
//import "acadi.idl";

[
	uuid(2C78F312-BB45-4456-BA3A-4CB19201A720),
	version(1.0),
	helpstring("NBIMIntellectRoadDesign 1.0 Type Library")
]
library NBIMIntellectRoadDesignLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");
	//----- If the following import fails then it means that the type library 
	//----- is not on the system path you can fix the problem in two ways:
	//----- 1. Add it to the system wide PATH environment variable
	//----- 2. Add it to the executable file list in Developer Studio. You can do
	//----- this in using the Tools/Option menu and then choosing the 'Directories'
	//----- tab and finally typing the full path at the Executable files section.

	//----- Importing english is ok here. Autodesk doesn't localize this idl/tlb.
	//----- axdb16enu.tlb is guaranteed to be available in all locales.
	//----- If you want to provide localized typelib then you must import
	//----- localized tlb here.
	importlib("axdb18enu.tlb");
};
